# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: everfree-phonetic-research
version: '0.0.1'
github: "faithanalog/everfree-phonetic-research"
license: MIT
author: "Artemis Everfree"
maintainer: "Artemis Everfree"
# synopsis: A new Haskeleton package.
# description: everfree-phonetic-research is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - edit-distance
  - hierarchical-clustering
  source-dirs: library

executables:
  everfree-phonetic-research:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - everfree-phonetic-research
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  everfree-phonetic-research-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - everfree-phonetic-research
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  everfree-phonetic-research-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - everfree-phonetic-research
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
